// DolzNFT cards seen on the DOLZ marketplace (card number, name, season and
// rarity per tier), for picking cards in the sniper settings. Generated from
// the card metadata captured in dolzMarketSeed; new cards can be typed by number.

export type DolzCatalogCard = { card: string; name: string; season: string | null; tiers: Record<string, string | null> };

export const DOLZ_CARD_CATALOG: DolzCatalogCard[] = [
  { card: "g0001", name: "Sia SIBERIA - Sexy Kitty", season: "1", tiers: {"60":"Rare","222":"Limited"} },
  { card: "g0002", name: "Emiri MOMOTA - Purple Fantasy", season: "3", tiers: {"140":"Rare","518":"Limited","700":null} },
  { card: "g0003", name: "Freya MAYER - Pink & Fluffy", season: "1", tiers: {"80":"Rare","296":"Limited"} },
  { card: "g0004", name: "Lana LANE - Milkmaid's Delight", season: "1", tiers: {"20":"Epic","296":"Limited"} },
  { card: "g0005", name: "Milan CHEEK - Stretched Pink", season: "4", tiers: {"200":"Rare","740":"Limited","1000":null} },
  { card: "g0007", name: "Mina von D - Squirm-inator", season: "1", tiers: {"80":"Rare","296":"Limited"} },
  { card: "g0009", name: "Agatha VEGA - Sun Kissed", season: "1", tiers: {"20":"Epic","296":"Limited"} },
  { card: "g0011", name: "BELKA - Babe-Watch", season: "1", tiers: {"80":"Rare","296":"Limited"} },
  { card: "g0012", name: "Melody MARKS - Take Meowt", season: "1", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0013", name: "Kelly COLLINS - Recess Time", season: "1", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0014", name: "Merida SAT - Home Run", season: "4", tiers: {"740":"Limited","1000":null} },
  { card: "g0015", name: "Alissa FOXY - Pin-Up For The Navy", season: "1", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0016", name: "Dolly DYSON - Cherry Dolly", season: "4", tiers: {"1000":null} },
  { card: "g0017", name: "Stefany KYLER - Not So Innocent", season: "2", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0018", name: "TOREE - Medieval Maiden", season: "Special Edition", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0019", name: "Josephine JACKSON - Topping Up My Tan", season: "4", tiers: {"740":"Limited","1000":null} },
  { card: "g0020", name: "Christy WHITE - Tightly Wrapped", season: "4", tiers: {"200":"Rare","740":"Limited","1000":null} },
  { card: "g0021", name: "Milena RAY - Ray-\u016bko", season: "4", tiers: {"200":"Rare","740":"Limited","1000":null} },
  { card: "g0022", name: "KITTY - Lovely Lace", season: "Special Edition", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0023", name: "Christy white & EVE SWEET - Hay Fever", season: "Special Edition", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0024", name: "Vanessa ALESSIA - Wine And Dine", season: "1", tiers: {"20":"Epic","80":"Rare","296":"Limited"} },
  { card: "g0025", name: "GEISHAKYD - Tough Love", season: "Special Edition", tiers: {"8":"Legendary","40":"Epic","160":"Rare","592":"Limited"} },
  { card: "g0026", name: "Alissa FOXY - Basketball Bunny", season: "5", tiers: {"40":"Epic","160":"Rare","592":"Limited","800":null} },
  { card: "g0028", name: "Josephine JACKSON - Flamming Red", season: "Off-Season", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0029", name: "Sonya BLAZE - Soft Touch", season: "1", tiers: {"296":"Limited"} },
  { card: "g0030", name: "Freya MAYER - Sexy Selfie", season: "2", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0031", name: "Camila NISSA - Shake It Up, Baby !", season: "5", tiers: {"155":"Rare","575":"Limited","777":null} },
  { card: "g0033", name: "Era QUEEN - Queen Fighter", season: "5", tiers: {"40":"Epic","160":"Rare","592":"Limited"} },
  { card: "g0034", name: "Yenifer CHACON - Spank Me Silly", season: "Off-Season", tiers: {"5":"Legendary","100":"Rare","370":"Limited"} },
  { card: "g0036", name: "Leona MIA - Net & Whisk", season: "Special Edition", tiers: {"89":"Rare","329":"Limited"} },
  { card: "g0037", name: "Andrea LUX - Lingerie De Lux", season: "Special Edition", tiers: {"22":"Epic","89":"Rare","329":"Limited"} },
  { card: "g0038", name: "Fanta SIE - A Walk In The Sun", season: "Special Edition", tiers: {"89":"Rare","329":"Limited"} },
  { card: "g0039", name: "Clemence AUDIARD - Ginger Warrior", season: "Off-Season", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0040", name: "Milena RAY - Feeling Blue?", season: "2", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0041", name: "Noemi MOON - Gorgeous Gingham", season: "Special Edition", tiers: {"160":"Rare","592":"Limited"} },
  { card: "g0042", name: "Silvia WISE - Not A Wise Girl", season: "Special Edition", tiers: {"89":"Rare","329":"Limited"} },
  { card: "g0043", name: "Agatha VEGA - Run For Lust", season: "5", tiers: {"60":"Epic","240":"Rare","888":"Limited","1200":null} },
  { card: "g0044", name: "Mathilda SCORPY - I Maid It For You", season: "5", tiers: {"7":"Legendary","140":"Rare","518":"Limited"} },
  { card: "g0046", name: "Svetlana U - Snow Maiden", season: "Special Edition", tiers: {"30":"Epic","120":"Rare","444":"Limited"} },
  { card: "g0047", name: "Lexi MONTANA - Fallin' For You", season: "7", tiers: {"600":null} },
  { card: "g0048", name: "SHELENA - Fleur De Cerisier", season: "5", tiers: {"8":"Legendary","160":"Rare","592":"Limited"} },
  { card: "g0049", name: "Christy WHITE - Burning Fever", season: "2", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0050", name: "Rika FANE - Hot In The Tepee", season: "4", tiers: {"200":"Rare","740":"Limited","1000":null} },
  { card: "g0051", name: "Dolly ORCHID - The Bear Necessities", season: "6", tiers: {"777":null} },
  { card: "g0052", name: "Barbie ROUS - Golden Nipples", season: "6", tiers: {"666":null} },
  { card: "g0053", name: "Ashby WINTER - Ashby Kitty", season: "6", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0054", name: "Sonya BLAZE - Your Remedy", season: "Off-Season", tiers: {"5":"Legendary","370":"Limited"} },
  { card: "g0055", name: "LALITA - Volcano Girl", season: "Special Edition", tiers: {"89":"Rare","329":"Limited"} },
  { card: "g0056", name: "Alissa foxy & KELLY COLLINS - Feathered Friends", season: "2", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0057", name: "Alissa FOXY - All Net", season: "Special Edition", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0058", name: "Nicole RAE - Nashville Bar Blues", season: "6", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0059", name: "RYANA - Peaches & Lace", season: "Special Edition", tiers: {"22":"Epic","89":"Rare","329":"Limited"} },
  { card: "g0060", name: "Nikki HILL - Cute Stripes", season: "Special Edition", tiers: {"120":"Rare","444":"Limited"} },
  { card: "g0061", name: "Rebecca VOLPETTI - Wet In The Net", season: "6", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0062", name: "KITTY - Flawless Victory", season: "2", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0063", name: "Kelly COLLINS - Transparent Ways", season: "6", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0064", name: "Sharon WHITE - Say Yes", season: "5", tiers: {"155":"Rare","575":"Limited"} },
  { card: "g0065", name: "OCTOKURO - Ninja's Sake", season: "2", tiers: {"2":"Epic","3":"Rare","100":"Rare","370":"Limited"} },
  { card: "g0066", name: "Paola HARD - Over The Rainbow", season: "6", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0067", name: "Lilly MAYS - Innocent Wiggle", season: "7", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0071", name: "Lana LANE - Juicy Peach", season: "2", tiers: {"5":"Legendary","25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0073", name: "Lilly BELLA - Fluffy Blues", season: "4", tiers: {"1000":null} },
  { card: "g0074", name: "Emiri MOMOTA - Light Breeze", season: "1", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0075", name: "Marina GOLD - Gold In Purple", season: "3", tiers: {"35":"Epic","140":"Rare","518":"Limited"} },
  { card: "g0076", name: "Sirena MILANO - Little Red Devil", season: "5", tiers: {"493":"Limited","666":null} },
  { card: "g0077", name: "Sky PIERCE - Rouge D\u00e9sir", season: "3", tiers: {"140":"Rare","518":"Limited","700":null} },
  { card: "g0078", name: "Agatha VEGA - Skin-deep Sensuality", season: "2", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0079", name: "BELKA - Wild Desire", season: "3", tiers: {"140":"Rare","518":"Limited","700":null} },
  { card: "g0081", name: "Lisa BELYS - Fluffy Handcuffs", season: "5", tiers: {"140":"Rare","518":"Limited"} },
  { card: "g0082", name: "Carla VYXX - Naughty Time", season: "2", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0083", name: "Linda BAKER - Lace In The Dark", season: "2", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0085", name: "AZELIA - The Elf Princess", season: "Special Edition", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0087", name: "Eve SWEET - The Dark Side", season: "2", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0088", name: "Monika MAY - Naughty Red Hood", season: "2", tiers: {"5":"Legendary","100":"Rare","370":"Limited"} },
  { card: "g0089", name: "Alissa FOXY - Sexy Knight", season: "3", tiers: {"35":"Epic","140":"Rare","518":"Limited","700":null} },
  { card: "g0090", name: "Nuria MILLAN - A Gilded Smacking", season: "4", tiers: {"50":"Epic","200":"Rare","1000":null} },
  { card: "g0091", name: "Lana LANE - Venice Beach Doll", season: "Off-Season", tiers: {"5":"Legendary","25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0092", name: "Kelly COLLINS - Sexy Princess", season: "3", tiers: {"700":null} },
  { card: "g0095", name: "Eva GENEROSI - Lollipop Tender", season: "5", tiers: {"220":"Rare","814":"Limited","1100":null} },
  { card: "g0096", name: "Carla VYXX - Curve Delight", season: "Off-Season", tiers: {"25":"Epic","370":"Limited","500":null} },
  { card: "g0099", name: "Melena maria RYA - Modern Burlesque", season: "3", tiers: {"700":null} },
  { card: "g0100", name: "Sia SIBERIA - Foxy K-Pop", season: "3", tiers: {"35":"Epic","140":"Rare","518":"Limited"} },
  { card: "g0101", name: "Lia SKY - Fasten The Belts", season: "Special Edition", tiers: {"22":"Epic","89":"Rare","329":"Limited"} },
  { card: "g0102", name: "Angelika GRAYS - Privately Pink", season: "5", tiers: {"740":"Limited","1000":null} },
  { card: "g0103", name: "Mina von D - Spidey's GF", season: "3", tiers: {"140":"Rare","518":"Limited"} },
  { card: "g0104", name: "Lily BLOSSOM - Blossoming Lace", season: "6", tiers: {"111":"Rare","411":"Limited","555":null} },
  { card: "g0105", name: "RYANA - Poolside Playmate", season: "7", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0106", name: "Kama OXI - Delicate Pink", season: "3", tiers: {"140":"Rare","700":null} },
  { card: "g0108", name: "TOREE - I'm A Legend", season: "4", tiers: {"50":"Epic","200":"Rare","740":"Limited"} },
  { card: "g0109", name: "Rebecca VOLPETTI - Toutes Griffes Dehors", season: "4", tiers: {"1000":null} },
  { card: "g0110", name: "Eva GENEROSI - The Bridesmaid", season: "Special Edition", tiers: {"89":"Rare","329":"Limited"} },
  { card: "g0111", name: "Lilly MAYS - Stripes Away !", season: "4", tiers: {"200":"Rare","740":"Limited","1000":null} },
  { card: "g0112", name: "Hope HEAVEN - Little Brown Jugs", season: "Special Edition", tiers: {"160":"Rare","592":"Limited"} },
  { card: "g0113", name: "SHELENA - Amethyst Afternoon", season: "3", tiers: {"35":"Epic","518":"Limited","700":null} },
  { card: "g0114", name: "Marica CHANELLE - I Want U", season: "5", tiers: {"750":null} },
  { card: "g0115", name: "Lana LANE - Living Fantasy", season: "3", tiers: {"35":"Epic","140":"Rare","518":"Limited"} },
  { card: "g0116", name: "GEORGIA - XOXO !", season: "6", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0117", name: "Dee VINE - SWAT This", season: "Special Edition", tiers: {"8":"Legendary","40":"Epic","160":"Rare","592":"Limited"} },
  { card: "g0118", name: "Stella CARDO - Let's Play Bunnies", season: "6", tiers: {"600":null} },
  { card: "g0119", name: "Dj SAKURA - Cabaret Style DJ", season: "6", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0120", name: "Vixi RAFI - Hard Puzzle", season: "Special Edition", tiers: {"4":"Legendary","89":"Rare","329":"Limited"} },
  { card: "g0121", name: "Dakota DOVE - Shake It Up", season: "7", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0122", name: "Dolly ORCHID - Classy Burgundy", season: "7", tiers: {"500":null} },
  { card: "g0123", name: "Claudia BAVEL - Take Off My Dress", season: "7", tiers: {"5":"Legendary","100":"Rare","370":"Limited"} },
  { card: "g0124", name: "Alexis CRYSTAL - Tangy Pink", season: "8", tiers: {"5":"Legendary","25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0125", name: "Emiri MOMOTA - Third Impact", season: "6", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0126", name: "Polly YANGS - I Will Punish You", season: "7", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0127", name: "Alice KISS - Attractive Cleavage", season: "7", tiers: {"500":null} },
  { card: "g0128", name: "Lia LIN - Lia The Diva", season: "7", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0129", name: "WIKKI - Gothic Night", season: "7", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0130", name: "Agatha VEGA - Wet And Waiting", season: "7", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0131", name: "Adriana SWEETBLONDE - Lucious In Lace", season: "Special Edition", tiers: {"89":"Rare","329":"Limited"} },
  { card: "g0132", name: "Ashby WINTER - The Winter Was Hot", season: "8", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0133", name: "Ave DEVA - I'm A Good Girl", season: "8", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0134", name: "AVERY - Trace Her", season: "8", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0137", name: "Vixi RAFI - Seductive Fighter", season: "8", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0138", name: "GEORGIA - Georgia's Cheers", season: "8", tiers: {"500":null} },
  { card: "g0139", name: "Reina OHARA - Arrest Me", season: "8", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0140", name: "Era QUEEN - Born On July 4th", season: "8", tiers: {"100":"Rare","370":"Limited","500":null} },
  { card: "g0141", name: "Chloe MOSS - Ch\u00e2timent Exquis", season: "8", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0142", name: "Lilly BELLA - This Net's For You", season: "8", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0143", name: "Lola RED - Executive Assistant", season: "8", tiers: {"500":null} },
  { card: "g0144", name: "Dolly ORCHID - Neon Schoolgirl", season: "8", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0146", name: "Novella NIGHT - Rising Pulse", season: "Special Edition", tiers: {"89":"Rare","329":"Limited"} },
  { card: "g0147", name: "Sally HUNTER - Ahegao's Bikini", season: "Special Edition", tiers: {"4":"Legendary","22":"Epic","89":"Rare","329":"Limited"} },
  { card: "g0148", name: "Anastasia CHERRY - Kitty Cheerleader", season: "9", tiers: {"30":"Epic","120":"Rare","444":"Limited"} },
  { card: "g0149", name: "Lily BLOSSOM - Undress Me Up !", season: "9", tiers: {"33":"Epic","130":"Rare","481":"Limited"} },
  { card: "g0150", name: "Christy LEY - A Hot Plumber", season: "Special Edition", tiers: {"89":"Rare","329":"Limited"} },
  { card: "g0151", name: "Marin NICO - Sakura No Hana", season: "9", tiers: {"5":"Legendary","25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0152", name: "RYANA - Chocolate Yoga", season: "9", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0153", name: "Freya MAYER - Chainsuck Lollipop", season: "8", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0154", name: "Lea PAM - Red Wolf", season: "9", tiers: {"120":"Rare","444":"Limited","600":null} },
  { card: "g0155", name: "Erika HEISS - Wet Curves", season: "Special Edition", tiers: {"89":"Rare","329":"Limited"} },
  { card: "g0156", name: "Noi FEJA - Veuve Noire", season: "Special Edition", tiers: {"89":"Rare","329":"Limited"} },
  { card: "g0157", name: "Vera JARW - Arresting Behavior", season: "9", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0158", name: "Megan LONGORIA - Promising Blue", season: "9", tiers: {"100":"Rare","370":"Limited"} },
  { card: "g0159", name: "HARENIKS - Just A Desire", season: "Special Edition", tiers: {"89":"Rare","329":"Limited"} },
  { card: "g0160", name: "Diana LAWRENCE - Sheer Elegance", season: "9", tiers: {"6":"Legendary","30":"Epic","120":"Rare","444":"Limited"} },
  { card: "g0161", name: "Dolly DYSON - The Latex Nurse", season: "9", tiers: {"5":"Legendary","25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0162", name: "Veronica LEAL - Oriental Desire", season: "9", tiers: {"35":"Epic","140":"Rare","518":"Limited"} },
  { card: "g0163", name: "Roksolana MIR - Wrap Me Tight", season: "Special Edition", tiers: {"89":"Rare","329":"Limited"} },
  { card: "g0164", name: "Reina OHARA - Kinky Pop D. Hunter", season: "9", tiers: {"700":null} },
  { card: "g0165", name: "Polly YANGS - Duchess Of Night", season: "10", tiers: {"30":"Epic","120":"Rare","444":"Limited"} },
  { card: "g0166", name: "Alexa MARTENS - Hot Gingham", season: "Special Edition", tiers: {"89":"Rare","329":"Limited"} },
  { card: "g0167", name: "Sky MOON - Sensual Copper", season: "Special Edition", tiers: {"4":"Legendary","22":"Epic","89":"Rare","329":"Limited"} },
  { card: "g0168", name: "SHELENA - Milky Cream", season: "10", tiers: {"7":"Legendary","35":"Epic","140":"Rare","518":"Limited","700":null} },
  { card: "g0169", name: "Hailey WHITE - Pink And Transparent", season: "Special Edition", tiers: {"4":"Legendary","22":"Epic","89":"Rare","329":"Limited"} },
  { card: "g0170", name: "Lana LANE - Sensuelle Rouge", season: "10", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0171", name: "Leya DESANTIS - Follow The Pink Lady", season: "Special Edition", tiers: {"22":"Epic","89":"Rare","329":"Limited"} },
  { card: "g0172", name: "Venus REY - Hot On The Sand", season: "10", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0173", name: "Sapphira A - Warning !", season: "Special Edition", tiers: {"89":"Rare","329":"Limited"} },
  { card: "g0174", name: "Kate ROSE - Cozy Body", season: "Special Edition", tiers: {"22":"Epic","89":"Rare","329":"Limited"} },
  { card: "g0175", name: "Anna BELLA - Deep Exploration", season: "10", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0176", name: "Lilly MAYS - Teddy Tails", season: "10", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0177", name: "Lea PAM - Great Ball Of Submission", season: "10", tiers: {"700":null} },
  { card: "g0178", name: "Lula STOCCH - Pinky Dressing Gown", season: "10", tiers: {"5":"Legendary","25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0179", name: "Jelena VOLKOV - Feeling Casual", season: "Special Edition", tiers: {"89":"Rare","329":"Limited"} },
  { card: "g0180", name: "Serena GOMES - Deusa Esmeralda", season: "Special Edition", tiers: {"4":"Legendary","89":"Rare","329":"Limited"} },
  { card: "g0182", name: "Dolly dyson & SOFIA RIVERS - Gehorche Mir !", season: "10", tiers: {"7":"Legendary","35":"Epic","140":"Rare","518":"Limited"} },
  { card: "g0183", name: "Sofia RIVERS - Sneak View", season: "11", tiers: {"5":"Legendary","25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0184", name: "GEORGIA - Toxic Seduction", season: "10", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0185", name: "Atlanta MORENO - Ocean Princess", season: "10", tiers: {"5":"Legendary","25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0186", name: "HARENIKS - Playing For Fun", season: "10", tiers: {"6":"Legendary","30":"Epic","120":"Rare","444":"Limited"} },
  { card: "g0187", name: "Samantha JOINER - The Net Of Pain", season: "Special Edition", tiers: {"22":"Epic","89":"Rare","329":"Limited"} },
  { card: "g0188", name: "Irene ROUSE - Tickling Breasts", season: "11", tiers: {"5":"Legendary","25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0189", name: "Valery PONCE - Ready To Ride", season: "Special Edition", tiers: {"89":"Rare","329":"Limited"} },
  { card: "g0190", name: "Barbie ROUS - California Team", season: "11", tiers: {"700":null} },
  { card: "g0191", name: "TOREE - Noces Blanches", season: "11", tiers: {"25":"Epic","100":"Rare","370":"Limited"} },
  { card: "g0194", name: "Angie LYNX - On The Banks Of Amour", season: "11", tiers: {"7":"Legendary","35":"Epic","140":"Rare","518":"Limited"} },
  { card: "g0195", name: "Alice SEDUCE - Mystery To Solve", season: "Special Edition", tiers: {"22":"Epic","89":"Rare","329":"Limited"} },
  { card: "g0198", name: "Gatita VEVE - Daring Rescue", season: "11", tiers: {"700":null} },
  { card: "g0203", name: "Clara TRINITY - Cheer Up", season: "11", tiers: {"5":"Legendary","25":"Epic","100":"Rare","370":"Limited"} },
];
